[project]
name = "word-breaker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyside6>=6.9.1",
]

[dependency-groups]
dev = [
    "ruff>=0.12.0",
    "pytest>=8.4.1",
    "pyinstaller>=6.14.1",
]
